name: 'CI'
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame --pre
          pip install coverage
          pip install pytest
  
  pylint :
    runs-on: ubuntu-latest
    steps:
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
        
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Run coverage
      run: |
        coverage run --branch --source=. -m pytest .  
            
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
